services:
  postgre_sql:
    container_name: postgres_container
    image: postgres:16.3-alpine
    restart: no
    environment:
      - POSTGRES_USER=${LOCAL_POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${LOCAL_POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${LOCAL_POSTGRESQL_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - postgre_sql:/var/lib/postgresql/data
    networks:
      app_net:
        ipv4_address: 172.18.0.30

  pg_admin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:8.10
    restart: no
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050
    networks:
      app_net:
        ipv4_address: 172.18.0.31

  # ollama:
  #   container_name: ollama_container
  #   image: ollama/ollama:0.3.4
  #   restart: no
  #   ports:
  #     - 11434:11434
  #   group_add:
  #     - video

volumes:
  postgre_sql:

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
