services:
  postgre_sql:
    container_name: postgres_container
    image: postgres:16.3-alpine
    restart: no #change to 'always' if model already deployed into development server
    environment: 
      - POSTGRES_USER=${LOCAL_POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${LOCAL_POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${LOCAL_POSTGRESQL_DATABASE}
    ports:
      - "${LOCAL_POSTGRESQL_PORT}:5432"
    volumes:
      - postgre_sql:/var/lib/postgresql/data
    networks:
      app_net:
        ipv4_address: 172.18.0.30
  
  pg_admin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:8
    restart: no #change to 'always' if model already deployed into development server
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "${PGADMIN_PORT}:5050"
    networks:
      app_net:
        ipv4_address: 172.18.0.31

  ollama:
    container_name: ollama_container
    image: ollama/ollama:0.1.45 #TODO: research how to utilize ROCM on RX6800s
    restart: no #change to 'always' if model already deployed into development server
    ports:
      - "11434:11434"
    volumes:
      - ollama:/var/lib/ollama/data
    group_add:
      - video
    
volumes:
  postgre_sql:
  ollama:

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16