services:
  postgre_sql:
    container_name: postgre_sql
    image: postgres:${POSTGRE_VERSION}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRE_USER}
      - POSTGRES_PASSWORD=${POSTGRE_PASSWORD}
      - POSTGRES_DB=${POSTGRE_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - postgre_sql:/var/lib/postgresql/data
    networks:
      stash_net:
        ipv4_address: 172.18.0.10

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    networks:
      stash_net:
        ipv4_address: 172.18.0.11
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgre_sql

  whatsapp_api:
    container_name: whatsapp_api
    image: taufikdev88/simplewhatsappapi:${WHATSAPP_API_VERSION}
    restart: always
    environment:
      - SESSION_SECRET=${WHATSAPP_API_SECRET_SESSION}
      - DB_CONNECTION_STRING=${WHATSAPP_API_CONNECTION}
    volumes:
      - whatsapp_api:/app/data
    ports:
      - 80:80
    networks:
      stash_net:
        ipv4_address: 172.18.0.12

volumes:
  postgre_sql:
  pgadmin:
  whatsapp_api:


networks:
  stash_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
