services:
  stash_postgre_sql:
    container_name: stash_postgre_sql
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - stash_postgre_sql:/var/lib/postgresql/data
    networks:
      stash_network:
        ipv4_address: 172.18.0.2


  stash_pg_admin:
    container_name: stash_pg_admin
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    networks:
      stash_network:
        ipv4_address: 172.18.0.3
    volumes:
      - stash_pg_admin:/var/lib/pgadmin
    depends_on:
      - stash_postgre_sql

  stash_whatsapp_api:
    container_name: stash_whatsapp_api
    image: taufikdev88/simplewhatsappapi:${WHATSAPP_API_VERSION}
    restart: always
    environment:
      - SESSION_SECRET=${WHATSAPP_API_SECRET_SESSION}
      - DB_CONNECTION_STRING=${WHATSAPP_API_CONNECTION}
    volumes:
      - stash_whatsapp_api:/app/data
    ports:
      - 80:80
    networks:
      stash_network:
        ipv4_address: 172.18.0.4

volumes:
  stash_postgre_sql:
  stash_pg_admin:
  stash_whatsapp_api:

networks:
  stash_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
