from dotenv import load_dotenv
import os

load_dotenv()

LOCAL_POSTGRESQL_USER = os.getenv("LOCAL_POSTGRESQL_USER")
LOCAL_POSTGRESQL_PASSWORD = os.getenv("LOCAL_POSTGRESQL_PASSWORD")
LOCAL_POSTGRESQL_HOST = os.getenv("LOCAL_POSTGRESQL_HOST")
LOCAL_POSTGRESQL_PORT = os.getenv("LOCAL_POSTGRESQL_PORT")
LOCAL_POSTGRESQL_DATABASE = os.getenv("LOCAL_POSTGRESQL_DATABASE")
LOCAL_POSTGRESQL_POOL_SIZE = os.getenv("LOCAL_POSTGRESQL_POOL_SIZE")
LOCAL_POSTGRESQL_MAX_OVERFLOW = os.getenv("LOCAL_POSTGRESQL_MAX_OVERFLOW")
ACCESS_TOKEN_EXPIRED=os.getenv("ACCESS_TOKEN_EXPIRED")
ACCESS_TOKEN_ALGORITHM=os.getenv("ACCESS_TOKEN_ALGORITHM")
ACCESS_TOKEN_SECRET_KEY=os.getenv("ACCESS_TOKEN_SECRET_KEY")
ACCESS_TOKEN_REFRESH_KEY=os.getenv("ACCESS_TOKEN_REFRESH_KEY")
REFRESH_TOKEN_EXPIRE_MINUTES=os.getenv("REFRESH_TOKEN_EXPIRE_MINUTES")
REFRESH_TOKEN_EXPIRE_HOURS=os.getenv("REFRESH_TOKEN_EXPIRE_HOURS")
REFRESH_TOKEN_EXPIRE_DAYS=os.getenv("REFRESH_TOKEN_EXPIRE_DAYS")