from dotenv import load_dotenv
import os

load_dotenv()

LOCAL_POSTGRESQL_USER = os.getenv("LOCAL_POSTGRESQL_USER")
LOCAL_POSTGRESQL_PASSWORD = os.getenv("LOCAL_POSTGRESQL_PASSWORD")
LOCAL_POSTGRESQL_HOST = os.getenv("LOCAL_POSTGRESQL_HOST")
LOCAL_POSTGRESQL_PORT = os.getenv("LOCAL_POSTGRESQL_PORT")
LOCAL_POSTGRESQL_DATABASE = os.getenv("LOCAL_POSTGRESQL_DATABASE")