name: python-unit-testing

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project
        poetry install --no-root

    - name: Run tests with coverage
      run: |
        source .venv/bin/activate
        coverage run --source=src/tests/auth/ -m pytest src/tests/auth/
        coverage report
        coverage html

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage-report.html
